default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: graphql_development

test:
  <<: *default
  database: graphql_test

production:
  <<: *default
  database: graphql_production
